dist: trusty
sudo: required

language: go
directories:
    - $HOME/.glide/cache
go:
  - 1.11.x

go_import_path: go.uber.org/cadence
addons:
  apt:
    packages:
      - gettext-base
      - libyaml-dev
      - openjdk-8-jre
      - python
      - python-dev
      - python-pip

before_install:

install:
  - go mod download

script:
  - make cover_ci

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

